// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://moxpmnooovdcffvztbbc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1veHBtbm9vb3ZkY2Zmdnp0YmJjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5NjkwOTgsImV4cCI6MjA2OTU0NTA5OH0.pYPwRwRgp5rREqnJND_8hxcunDgUOestKOYl9VI9aVs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});